### ISSUE TITLE
[BUG] add, delete users, get rid of default ABC

### ISSUE THREAD

**Issue by hubbertsmith** [linuxserver/docker-webtop#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I looked for, and did not find
a way to add more than one user
a way to get rid of 'abc' default account

I tried the usual modifications of docker-image /etc/passwd. did not work

### Expected Behavior

need docs or methods:
to add more than one user
to get rid of 'abc' default account

User A screen desktop should be independent and separate than User B desktop

### Steps To Reproduce

edit /etc/passwd -- still starts with default abc

### Environment

```markdown
- OS:ubuntu 22.04
- How docker service was installed: snap
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -itd \
  --env-file /home/hubbert/webtop/.env \
  -p 3000:3000/tcp  \
  -v /run/snapd.socket:/run/snapd.socket \
  --cap-add=NET_ADMIN \
  --device=/dev/net/tun \
  --network=bridge \
  --mount source=i4voll.3,target=/i4 \
  --restart unless-stopped \
  hs5:latest
```

### Container logs

```bash
docker logs 89cb11ba5566
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

.+....+...+..+................+.........+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+...............+........+....+........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..........+.............+..+....+...+..+....+..+....+...........+....+...+.....+.......+........+.......+...+...+..+.............+...+.....+.....................+.........+.......+...............+..+......+......+.+...+..........................................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...+......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+..+...+.........................+...+.....+.+..............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+..+...+.+......+...+.....+...+...+.+........+..................+....+...........+.........+.+.....+.........+..........+...............+...+........+...+....+...........+...............+....+..+.+........+......+......+...+......+.+...+......+.....+...+......+....+......+..+...+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[ls.io-init] done.

Xvnc KasmVNC 1.1.0 - built Jun 17 2023 18:54:12
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

Error: Connection refused
    at PulseAudioContext.<anonymous> (/kclient/node_modules/pulseaudio2/lib/pulse.js:120:36)
    at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Kclient was unable to init audio, it is possible your host lacks support!!!!
Error: Access denied
    at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Kclient was unable to init audio, it is possible your host lacks support!!!!
```

**Comment by Roxedus** [comment]
Multi-user support is out of the scope of this project.

**Comment by hubbertsmith** [comment]
thanks again for your reply.
I understand "out of scope", no problem
perhaps I can fix it from my end? and I will happily share the work back to
linuxserver.io
breadcrumbs? where and how is 'abc' default account defined? any ideas on
where to look?   I will not trouble you any further, thanks

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by Roxedus** [comment]
Base images and init scripts.
